import { CalendarPlus, CarFront, ClipboardPlus, Pencil, Plus } from "lucide-react";
import { useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import type { AppOutlet } from "../app/AppShell";
import { Button, Card, EmptyState, inputClass, Spinner } from "../components/ui";
import { customerName } from "../lib/format";
import { useCrm } from "../features/crm/useCrm";

export function CarsPage() {
  const { openEntity } = useOutletContext<AppOutlet>(); const crm = useCrm(); const [filter, setFilter] = useState("");
  const items = useMemo(() => { const q = filter.trim().toLocaleLowerCase("ru"); return (crm.data?.cars ?? []).filter((item) => !q || `${item.brand} ${item.model} ${item.plate_number ?? ""} ${item.vin ?? ""}`.toLocaleLowerCase("ru").includes(q)); }, [crm.data?.cars, filter]);
  if (crm.isPending) return <Spinner />;
  return <div className="grid gap-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-apex">АВТОПАРК</p><h1 className="text-3xl font-black">Автомобили</h1><p className="mt-1 text-muted">{crm.data?.cars.length ?? 0} автомобилей</p></div><Button onClick={() => openEntity({ kind: "car" })}><Plus size={18} />Добавить автомобиль</Button></header><input className={inputClass} value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Фильтр по марке, модели, номеру или VIN" aria-label="Фильтр автомобилей" />
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.length ? items.map((item) => { const owner = crm.data?.customers.find((customer) => customer.id === item.customer_id); return <Card key={item.id}><div className="flex items-start gap-3"><div className="grid size-12 shrink-0 place-items-center rounded-xl bg-apex/10 text-apex"><CarFront /></div><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-black">{item.brand} {item.model}</h2><p className="text-sm text-muted">{item.year || "Год не указан"}{item.plate_number ? ` · ${item.plate_number}` : ""}</p></div><Button variant="ghost" className="size-11 p-0" onClick={() => openEntity({ kind: "car", value: item })} aria-label={`Изменить ${item.brand} ${item.model}`}><Pencil size={18} /></Button></div><dl className="my-4 grid grid-cols-2 gap-2 rounded-xl bg-panel-soft p-3 text-sm"><div><dt className="text-muted">Владелец</dt><dd className="mt-1 font-semibold">{customerName(owner?.full_name)}</dd></div><div><dt className="text-muted">Пробег</dt><dd className="mt-1 font-semibold">{item.mileage ? `${item.mileage.toLocaleString("ru-RU")} км` : "Не указан"}</dd></div><div className="col-span-2"><dt className="text-muted">VIN</dt><dd className="mt-1 break-all font-mono text-xs">{item.vin || "Не указан"}</dd></div></dl><div className="grid grid-cols-2 gap-2"><Button variant="secondary" onClick={() => openEntity({ kind: "appointment", carId: item.id })}><CalendarPlus size={16} />Запись</Button><Button variant="secondary" onClick={() => openEntity({ kind: "order", carId: item.id })}><ClipboardPlus size={16} />Заказ</Button></div></Card>; }) : <div className="md:col-span-2 xl:col-span-3"><EmptyState>Автомобили не найдены</EmptyState></div>}</div>
  </div>;
}
