import { CarFront, Pencil, Plus, UserPlus } from "lucide-react";
import { useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import type { AppOutlet } from "../app/AppShell";
import { Button, Card, EmptyState, inputClass, Spinner } from "../components/ui";
import { customerName } from "../lib/format";
import { useCrm } from "../features/crm/useCrm";

export function CustomersPage() {
  const { openEntity, openDetail } = useOutletContext<AppOutlet>(); const crm = useCrm(); const [filter, setFilter] = useState(""); const [visible, setVisible] = useState(24);
  const items = useMemo(() => { const q = filter.trim().toLocaleLowerCase("ru"); return (crm.data?.customers ?? []).filter((item) => !q || `${item.full_name} ${item.phone ?? ""}`.toLocaleLowerCase("ru").includes(q)); }, [crm.data?.customers, filter]);
  if (crm.isPending) return <Spinner />;
  return <div className="grid min-w-0 gap-5"><header className="flex min-w-0 flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="text-sm font-bold text-apex">БАЗА CRM</p><h1 className="break-words text-3xl font-black">Клиенты</h1><p className="mt-1 text-muted">{crm.data?.customers.length ?? 0} карточек</p></div><Button onClick={() => openEntity({ kind: "customer" })}><UserPlus size={18} />Новый клиент</Button></header><input className={inputClass} value={filter} onChange={(event) => { setFilter(event.target.value); setVisible(24); }} placeholder="Фильтр по имени или телефону" aria-label="Фильтр клиентов" />
    <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{items.length ? items.slice(0, visible).map((item) => { const cars = crm.data?.cars.filter((car) => car.customer_id === item.id) ?? []; return <Card key={item.id} className="group flex cursor-pointer flex-col overflow-hidden p-0 transition hover:-translate-y-0.5 hover:border-apex/50" onClick={() => openDetail({ kind: "customer", value: item })}><div className="flex min-w-0 items-start gap-3 border-b border-line bg-gradient-to-br from-panel-soft to-panel p-4"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-info/10 text-info"><UserPlus size={21}/></div><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">Клиент</p><h2 className="break-words text-lg font-black">{customerName(item.full_name)}</h2><p className="mt-1 break-all text-sm text-muted">{item.phone || "Телефон не указан"}</p></div><Button variant="ghost" className="size-10 shrink-0 p-0" onClick={(event) => { event.stopPropagation(); openEntity({ kind: "customer", value: item }); }} aria-label={`Изменить клиента ${customerName(item.full_name)}`}><Pencil size={18} /></Button></div><div className="flex-1 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide text-muted">Автомобили</span><strong className="rounded-full bg-apex/10 px-2 py-1 text-xs text-apex">{cars.length}</strong></div><div className="grid gap-2">{cars.slice(0, 3).map((car) => <div key={car.id} className="flex min-w-0 items-center gap-2 rounded-xl border border-line/70 bg-canvas/50 p-3 text-sm"><CarFront className="shrink-0 text-apex" size={18} /><span className="min-w-0 break-words font-semibold">{car.brand} {car.model}{car.plate_number ? ` · ${car.plate_number}` : ""}</span></div>)}{!cars.length && <p className="rounded-xl bg-canvas/50 p-3 text-sm text-muted">Автомобилей пока нет</p>}{cars.length > 3 && <p className="text-sm text-muted">Ещё автомобилей: {cars.length - 3}</p>}</div></div><div className="border-t border-line p-3"><Button variant="secondary" className="w-full" onClick={(event) => { event.stopPropagation(); openEntity({ kind: "car", customerId: item.id }); }}><Plus size={16} />Добавить автомобиль</Button><p className="mt-2 text-center text-xs font-semibold text-apex">Открыть карточку клиента →</p></div></Card>; }) : <div className="md:col-span-2 xl:col-span-3"><EmptyState>Клиенты не найдены</EmptyState></div>}</div>
    {visible < items.length && <Button variant="secondary" onClick={() => setVisible((value) => value + 24)}>Показать ещё ({items.length - visible})</Button>}
  </div>;
}
