import { CarFront, Pencil, Plus, UserPlus } from "lucide-react";
import { useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import type { AppOutlet } from "../app/AppShell";
import { Button, Card, EmptyState, inputClass, Spinner } from "../components/ui";
import { customerName } from "../lib/format";
import { useCrm } from "../features/crm/useCrm";

export function CustomersPage() {
  const { openEntity, openDetail } = useOutletContext<AppOutlet>(); const crm = useCrm(); const [filter, setFilter] = useState(""); const [visible, setVisible] = useState(24);
  const items = useMemo(() => { const q = filter.trim().toLocaleLowerCase("ru"); return (crm.data?.customers ?? []).filter((item) => !q || `${item.full_name} ${item.phone ?? ""}`.toLocaleLowerCase("ru").includes(q)); }, [crm.data?.customers, filter]);
  if (crm.isPending) return <Spinner />;
  return <div className="grid min-w-0 gap-5"><header className="flex min-w-0 flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="text-sm font-bold text-apex">БАЗА CRM</p><h1 className="break-words text-3xl font-black">Клиенты</h1><p className="mt-1 text-muted">{crm.data?.customers.length ?? 0} карточек</p></div><Button onClick={() => openEntity({ kind: "customer" })}><UserPlus size={18} />Новый клиент</Button></header><input className={inputClass} value={filter} onChange={(event) => { setFilter(event.target.value); setVisible(24); }} placeholder="Фильтр по имени или телефону" aria-label="Фильтр клиентов" />
    <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{items.length ? items.slice(0, visible).map((item) => { const cars = crm.data?.cars.filter((car) => car.customer_id === item.id) ?? []; return <Card key={item.id} className="flex cursor-pointer flex-col transition hover:border-apex/50" onClick={() => openDetail({ kind: "customer", value: item })}><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-lg font-black">{customerName(item.full_name)}</h2><p className="mt-1 break-all text-sm text-muted">{item.phone || "Телефон не указан"}</p></div><Button variant="ghost" className="size-11 shrink-0 p-0" onClick={(event) => { event.stopPropagation(); openEntity({ kind: "customer", value: item }); }} aria-label={`Изменить клиента ${customerName(item.full_name)}`}><Pencil size={18} /></Button></div><div className="mt-5 grid gap-2">{cars.slice(0, 3).map((car) => <div key={car.id} className="flex min-w-0 items-center gap-2 rounded-xl bg-panel-soft p-3 text-sm"><CarFront className="shrink-0 text-apex" size={18} /><span className="min-w-0 break-words">{car.brand} {car.model}{car.plate_number ? ` · ${car.plate_number}` : ""}</span></div>)}{cars.length > 3 && <p className="text-sm text-muted">Ещё автомобилей: {cars.length - 3}</p>}</div><Button variant="secondary" className="mt-auto pt-3" onClick={(event) => { event.stopPropagation(); openEntity({ kind: "car", customerId: item.id }); }}><Plus size={16} />Добавить автомобиль</Button><p className="mt-3 text-center text-xs font-semibold text-apex">Нажмите для подробной карточки</p></Card>; }) : <div className="md:col-span-2 xl:col-span-3"><EmptyState>Клиенты не найдены</EmptyState></div>}</div>
    {visible < items.length && <Button variant="secondary" onClick={() => setVisible((value) => value + 24)}>Показать ещё ({items.length - visible})</Button>}
  </div>;
}
