import { Banknote, ChevronDown, PackageOpen, TrendingUp, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { useOutletContext, useSearchParams } from "react-router-dom";
import type { AppOutlet } from "../app/AppShell";
import { Button, Card, EmptyState, Spinner } from "../components/ui";
import { formatDateTime, money, parseCrmDate } from "../lib/format";
import { useCrm } from "../features/crm/useCrm";

type Period = 1 | 7 | 30 | 0;
type Section = "revenue" | "labor" | "parts" | "profit" | null;
export function FinancePage() {
  const crm = useCrm(); const { openDetail } = useOutletContext<AppOutlet>(); const [params] = useSearchParams(); const [period, setPeriod] = useState<Period>(params.get("period") === "today" ? 1 : 30); const [open, setOpen] = useState<Section>("profit"); const [ordersOpen, setOrdersOpen] = useState(true);
  const customerId = Number(params.get("customer_id")) || null;
  const orders = useMemo(() => { const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); if (period > 1) start.setDate(start.getDate() - (period - 1)); const carIds = new Set((crm.data?.cars ?? []).filter((car) => car.customer_id === customerId).map((car) => car.id)); return (crm.data?.orders ?? []).filter((item) => ["ready", "completed"].includes(item.status) && item.completed_at && (!customerId || carIds.has(item.car_id)) && (!period || parseCrmDate(item.completed_at) >= start) && parseCrmDate(item.completed_at) <= now); }, [crm.data?.cars, crm.data?.orders, customerId, period]);
  if (crm.isPending) return <Spinner />;
  const labor = orders.reduce((sum, x) => sum + x.labor_revenue, 0); const partsRevenue = orders.reduce((sum, x) => sum + x.parts_revenue, 0); const partsCost = orders.reduce((sum, x) => sum + x.parts_cost, 0); const extraPartsProfit = orders.reduce((sum, x) => sum + x.parts_profit, 0); const markup = partsRevenue - partsCost + extraPartsProfit; const revenue = labor + partsRevenue; const profit = orders.reduce((sum, x) => sum + x.profit, 0); const margin = revenue ? Math.round(profit / revenue * 100) : 0;
  const sections = [
    { key: "revenue" as const, label: "Выручка", value: revenue, hint: `${orders.length} заказов`, icon: Banknote, color: "text-info", rows: [["Работы", labor], ["Продажа запчастей", partsRevenue]] as const },
    { key: "labor" as const, label: "Доход от работ", value: labor, hint: `${revenue ? Math.round(labor / revenue * 100) : 0}% выручки`, icon: Wrench, color: "text-apex", rows: [["Оплачено за работы", labor]] as const },
    { key: "parts" as const, label: "Запчасти и наценка", value: markup, hint: `Закупка ${money(partsCost)}`, icon: PackageOpen, color: "text-info", rows: [["Продажа", partsRevenue], ["Закупка", partsCost], ["Доп. прибыль", extraPartsProfit], ["Наценка / прибыль", markup]] as const },
    { key: "profit" as const, label: "Чистый заработок", value: profit, hint: `Маржинальность ${margin}%`, icon: TrendingUp, color: "text-success", rows: [["Работы", labor], ["Прибыль с запчастей", markup], ["Итого", profit]] as const },
  ];
  return <div className="grid min-w-0 gap-6"><header><p className="text-sm font-bold text-apex">АНАЛИТИКА</p><h1 className="text-3xl font-black">Финансы</h1><p className="mt-1 text-muted">Нажмите на показатель, чтобы увидеть состав суммы</p></header><div className="flex max-w-full gap-2 overflow-x-auto pb-1">{([[1,"Сегодня"],[7,"7 дней"],[30,"30 дней"],[0,"Всё время"]] as const).map(([value, label]) => <Button className="shrink-0" key={value} variant={period === value ? "primary" : "secondary"} onClick={() => setPeriod(value)}>{label}</Button>)}</div>
    <section className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-4">{sections.map(({ key, label, value, hint, icon: Icon, color, rows }) => <Card key={key} className={`cursor-pointer transition hover:border-apex/50 ${open === key ? "border-apex/60" : ""}`} onClick={() => setOpen(open === key ? null : key)}><div className="flex items-start justify-between"><Icon className={color} /><ChevronDown className={`text-muted transition ${open === key ? "rotate-180 text-apex" : ""}`} /></div><p className="mt-5 text-sm text-muted">{label}</p><strong className="mt-1 block break-words text-2xl font-black">{money(value)}</strong><p className="mt-1 text-xs text-muted">{hint}</p>{open === key && <dl className="mt-4 grid gap-2 border-t border-line pt-3">{rows.map(([name, amount]) => <div key={name} className="flex min-w-0 justify-between gap-3 text-sm"><dt className="text-muted">{name}</dt><dd className="shrink-0 font-bold">{money(amount)}</dd></div>)}</dl>}</Card>)}</section>
    <Card><button type="button" className="flex w-full flex-wrap items-center justify-between gap-3 text-left" onClick={() => setOrdersOpen((value) => !value)}><div><h2 className="text-lg font-black">Заказы в расчёте</h2><p className="mt-1 text-sm text-muted">Подробная расшифровка каждой суммы</p></div><span className="flex items-center gap-2"><strong className="text-apex">{orders.length}</strong><ChevronDown className={`transition ${ordersOpen ? "rotate-180" : ""}`} /></span></button>{ordersOpen && <div className="mt-4 grid gap-2">{orders.length ? orders.map((item) => <button key={item.id} type="button" onClick={() => openDetail({ kind: "order", value: item })} className="grid min-w-0 gap-2 rounded-xl bg-panel-soft p-3 text-left transition hover:bg-line sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><p className="break-words font-bold">#{item.id} · {item.brand} {item.model}</p><p className="mt-1 break-words text-sm text-muted">{formatDateTime(item.completed_at || item.created_at)} · {item.description}</p></div><div className="grid grid-cols-2 gap-x-4 text-sm sm:text-right"><span className="text-muted">Выручка</span><strong>{money(item.labor_revenue + item.parts_revenue)}</strong><span className="text-muted">Прибыль</span><strong className="text-success">{money(item.profit)}</strong></div></button>) : <EmptyState>За выбранный период заказов нет</EmptyState>}</div>}</Card>
    <Card className="grid gap-3 sm:grid-cols-3"><Metric label="Средний чек" value={money(orders.length ? revenue / orders.length : 0)} /><Metric label="Средняя прибыль" value={money(orders.length ? profit / orders.length : 0)} /><Metric label="Маржинальность" value={`${margin}%`} /></Card>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-panel-soft p-4"><p className="text-sm text-muted">{label}</p><strong className="mt-1 block text-xl font-black">{value}</strong></div>; }
