import { Bell, Blocks, Building2, Check, ChevronRight, Cloud, KeyRound, MonitorCog, RotateCcw, ShieldCheck, Smartphone, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Button, Card, Field, inputClass } from "../components/ui";
import { api, ApiError } from "../lib/api";
import { queryClient } from "../lib/query";
import type { StaffRole } from "../lib/types";
import { defaultSettings, saveSettings, useAppSettings, type AppSettings, type ModuleKey } from "../lib/settings";

const moduleItems: { key: ModuleKey; title: string; description: string }[] = [
  { key: "calendar", title: "Календарь", description: "Записи, загрузка постов и расписание" }, { key: "orders", title: "Заказ-наряды", description: "Работы, запчасти и статусы ремонта" },
  { key: "diagnostics", title: "Диагностика", description: "Чек-листы, фото и заключения" }, { key: "customers", title: "Клиенты", description: "Контакты и история обращений" },
  { key: "cars", title: "Автомобили", description: "Карточки машин и сервисная история" }, { key: "finance", title: "Финансы", description: "Выручка, расходы и прибыль" },
  { key: "trash", title: "Корзина", description: "Восстановление удалённых данных" },
];
function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (v: boolean) => void; label: string }) { return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative h-7 w-12 shrink-0 rounded-full transition focus-visible:outline-2 focus-visible:outline-apex ${checked ? "bg-apex" : "bg-line"}`}><span className={`absolute top-1 size-5 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`} /></button>; }
function Row({ title, description, checked, onChange }: { title: string; description: string; checked: boolean; onChange: (v: boolean) => void }) { return <div className="flex items-center gap-4 border-t border-line py-4 first:border-0 first:pt-0 last:pb-0"><div className="min-w-0 flex-1"><p className="font-bold">{title}</p><p className="mt-1 text-sm text-muted">{description}</p></div><Toggle checked={checked} onChange={onChange} label={title} /></div>; }
function Heading({ icon: Icon, title, text }: { icon: typeof Bell; title: string; text: string }) { return <div className="mb-5 flex items-center gap-3"><Icon className="text-apex" /><div><h2 className="text-xl font-black">{title}</h2><p className="text-sm text-muted">{text}</p></div></div>; }
function Integration({ name, status }: { name: string; status: string }) { return <div className="flex items-center gap-3 border-t border-line py-3 first:border-0 first:pt-0"><Cloud size={18} className="text-muted" /><span className="min-w-0 flex-1"><strong className="block">{name}</strong><span className="text-sm text-muted">{status}</span></span><ChevronRight size={18} className="text-muted" /></div>; }

const roleNames: Record<string, string> = { owner: "Владелец", admin: "Администратор", service_advisor: "Мастер-приёмщик", mechanic: "Механик", accountant: "Бухгалтер", viewer: "Наблюдатель" };

function StaffSettings() {
  const staff = useQuery({ queryKey: ["settings-staff"], queryFn: api.staff, retry: false });
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<{ full_name: string; username: string; password: string; role: StaffRole }>({ full_name: "", username: "", password: "", role: "service_advisor" });
  const [resetId, setResetId] = useState<number | null>(null);
  const [resetPassword, setResetPassword] = useState("");
  const create = useMutation({ mutationFn: api.createStaff, onSuccess: async () => { setOpen(false); setForm({ full_name: "", username: "", password: "", role: "service_advisor" }); await queryClient.invalidateQueries({ queryKey: ["settings-staff"] }); } });
  const update = useMutation({ mutationFn: ({ id, active }: { id: number; active: boolean }) => api.updateStaff(id, { active }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["settings-staff"] }) });
  const reset = useMutation({ mutationFn: ({ id, password }: { id: number; password: string }) => api.updateStaff(id, { password }), onSuccess: async () => { setResetId(null); setResetPassword(""); await queryClient.invalidateQueries({ queryKey: ["settings-staff"] }); } });
  const error = create.error instanceof ApiError ? create.error.message : "";
  if (staff.error instanceof ApiError && staff.error.status === 403) return <Card><Heading icon={UsersRound} title="Сотрудники" text="Управление сотрудниками доступно владельцу и администратору" /></Card>;
  return <Card><div className="flex flex-wrap items-start gap-3"><UsersRound className="text-apex" /><div className="min-w-0 flex-1"><h2 className="text-xl font-black">Сотрудники и права доступа</h2><p className="text-sm text-muted">У каждого сотрудника собственные логин, пароль и роль</p></div><Button variant="secondary" onClick={() => setOpen(!open)}><UsersRound size={18} />Добавить сотрудника</Button></div>
    {open && <form className="mt-5 grid gap-3 rounded-2xl border border-line bg-canvas p-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); create.mutate(form); }}><Field label="Имя сотрудника"><input className={inputClass} value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} required /></Field><Field label="Логин"><input className={inputClass} value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} autoComplete="off" required /></Field><Field label="Временный пароль (от 10 символов)"><input className={inputClass} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} minLength={10} autoComplete="new-password" required /></Field><Field label="Роль"><select className={inputClass} value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as StaffRole })}><option value="admin">Администратор</option><option value="service_advisor">Мастер-приёмщик</option><option value="mechanic">Механик</option><option value="accountant">Бухгалтер</option><option value="viewer">Наблюдатель</option></select></Field>{error && <p className="text-sm text-danger sm:col-span-2">{error}</p>}<div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={create.isPending}>Создать учётную запись</Button><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Отмена</Button></div></form>}
    <p className="mt-4 rounded-xl bg-info/10 p-3 text-sm text-muted">Пароли не отображаются в панели безопасности: система хранит только защищённый хэш. Если пароль потерян, задайте сотруднику новый.</p>
    <div className="mt-5 divide-y divide-line">{staff.isLoading && <p className="py-4 text-muted">Загружаю сотрудников…</p>}{staff.data?.map((member) => <div key={member.id} className="grid gap-3 py-4 sm:flex sm:flex-wrap sm:items-center"><span className={`size-2 rounded-full ${member.active ? "bg-success" : "bg-muted"}`} /><div className="min-w-48 flex-1"><p className="font-bold">{member.full_name}</p><p className="text-sm text-muted">{member.username} · {roleNames[member.role]}</p></div>{member.role !== "owner" && <div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={update.isPending} onClick={() => update.mutate({ id: member.id, active: !member.active })}>{member.active ? "Отключить доступ" : "Включить доступ"}</Button><Button variant="secondary" onClick={() => { setResetId(resetId === member.id ? null : member.id); setResetPassword(""); }}>Сменить пароль</Button></div>}{resetId === member.id && <form className="grid gap-2 rounded-xl border border-line bg-canvas p-3 sm:col-span-2 sm:grid-cols-[1fr_auto]" onSubmit={(event) => { event.preventDefault(); reset.mutate({ id: member.id, password: resetPassword }); }}><input className={inputClass} type="password" minLength={10} autoComplete="new-password" placeholder="Новый пароль, минимум 10 символов" value={resetPassword} onChange={(event) => setResetPassword(event.target.value)} required /><Button type="submit" disabled={reset.isPending || resetPassword.length < 10}>{reset.isPending ? "Сохраняю…" : "Сохранить пароль"}</Button>{reset.error instanceof ApiError && <p className="text-sm text-danger sm:col-span-2">{reset.error.message}</p>}</form>}</div>)}</div>
  </Card>;
}

export function SettingsPage() {
  const stored = useAppSettings(); const [settings, setSettings] = useState<AppSettings>(stored); const [saved, setSaved] = useState(false);
  const workspace = useQuery({ queryKey: ["workspace"], queryFn: api.workspace, retry: false });
  const saveWorkspace = useMutation({ mutationFn: api.updateWorkspace, onSuccess: async (value) => { setSettings((current) => ({ ...current, workspaceName: value.name, city: value.city ?? "" })); await queryClient.invalidateQueries({ queryKey: ["account"] }); } });
  const [passwords, setPasswords] = useState({ current: "", next: "" });
  const changePassword = useMutation({ mutationFn: () => api.changePassword(passwords.current, passwords.next), onSuccess: () => setPasswords({ current: "", next: "" }) });
  useEffect(() => { if (workspace.data) setSettings((current) => ({ ...current, workspaceName: workspace.data.name, city: workspace.data.city ?? "" })); }, [workspace.data]);
  const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => { setSaved(false); setSettings((current) => ({ ...current, [key]: value })); };
  const save = () => { saveSettings(settings); saveWorkspace.mutate({ name: settings.workspaceName, city: settings.city }); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <div className={`mx-auto grid max-w-5xl gap-6 ${settings.compactMode ? "settings-compact" : ""}`}>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-wide text-apex">УПРАВЛЕНИЕ</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Настройки</h1><p className="mt-2 max-w-2xl text-muted">Настройте рабочее пространство, доступные модули и поведение Apex CRM.</p></div><Button onClick={save}>{saved && <Check size={18} />}{saved ? "Сохранено" : "Сохранить изменения"}</Button></header>
    <Card><Heading icon={Building2} title="Рабочее пространство" text="Общие данные вашей организации" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Название автосервиса"><input className={inputClass} value={settings.workspaceName} onChange={(e) => update("workspaceName", e.target.value)} /></Field><Field label="Город и часовой пояс"><input className={inputClass} value={settings.city} onChange={(e) => update("city", e.target.value)} /></Field></div><p className="mt-4 rounded-xl bg-panel-soft p-3 text-sm text-muted">В общей версии здесь появятся филиалы, рабочие посты, нормы времени, валюта, налоги, реквизиты и шаблоны документов.</p></Card>
    <Card><Heading icon={Blocks} title="Модули приложения" text="Отключённые разделы исчезнут из бокового меню" /><div className="grid gap-x-6 md:grid-cols-2">{moduleItems.map((item) => <Row key={item.key} title={item.title} description={item.description} checked={settings.modules[item.key]} onChange={(value) => update("modules", { ...settings.modules, [item.key]: value })} />)}</div></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card><Heading icon={Bell} title="Уведомления" text="Что требует вашего внимания" /><Row title="На этом устройстве" description="Показывать системные уведомления" checked={settings.desktopNotifications} onChange={(v) => update("desktopNotifications", v)} /><Row title="Напоминания о записи" description="Перед визитом клиента" checked={settings.appointmentReminders} onChange={(v) => update("appointmentReminders", v)} /><Row title="Статусы заказов" description="Готовность, задержки и согласования" checked={settings.orderStatusNotifications} onChange={(v) => update("orderStatusNotifications", v)} /><Row title="Итоги дня" description="Краткая вечерняя сводка" checked={settings.dailySummary} onChange={(v) => update("dailySummary", v)} /></Card>
    <Card><Heading icon={MonitorCog} title="Интерфейс" text="Вид приложения на этом устройстве" /><Row title="Компактный режим" description="Меньше отступов, больше данных" checked={settings.compactMode} onChange={(v) => update("compactMode", v)} /><Row title="Минимум анимации" description="Сократить движения интерфейса" checked={settings.reduceMotion} onChange={(v) => update("reduceMotion", v)} /><div className="mt-4 flex gap-3 rounded-xl bg-panel-soft p-3 text-sm text-muted"><Smartphone size={20} className="shrink-0 text-info" />Эти параметры сохраняются на текущем устройстве.</div></Card></div>
    <StaffSettings />
    <div className="grid gap-6 lg:grid-cols-2"><Card><Heading icon={Cloud} title="Интеграции" text="Связь с внешними сервисами" /><Integration name="Поставщики запчастей" status="Настраивается на сервере" /><Integration name="Телефония и мессенджеры" status="Не подключено" /><Integration name="Онлайн-касса и бухгалтерия" status="Не подключено" /><Integration name="Календари и вебхуки" status="Не подключено" /></Card>
    <Card><Heading icon={ShieldCheck} title="Безопасность" text="Сессии и защита учётной записи" /><Field label="Автоблокировка при бездействии"><select className={inputClass} value={settings.autoLockMinutes} onChange={(e) => update("autoLockMinutes", Number(e.target.value))}><option value={0}>Не блокировать</option><option value={15}>Через 15 минут</option><option value={30}>Через 30 минут</option><option value={60}>Через 1 час</option></select></Field><div className="mt-4 grid gap-3"><Field label="Текущий пароль"><input className={inputClass} type="password" value={passwords.current} onChange={(e) => setPasswords({ ...passwords, current: e.target.value })} /></Field><Field label="Новый пароль (от 10 символов)"><input className={inputClass} type="password" minLength={10} value={passwords.next} onChange={(e) => setPasswords({ ...passwords, next: e.target.value })} /></Field>{changePassword.error instanceof ApiError && <p className="text-sm text-danger">{changePassword.error.message}</p>}<Button variant="secondary" disabled={!passwords.current || passwords.next.length < 10 || changePassword.isPending} onClick={() => changePassword.mutate()}><KeyRound size={18} />Изменить пароль</Button></div></Card></div>
    <Card className="flex flex-wrap items-center gap-4"><RotateCcw className="text-muted" /><div className="min-w-0 flex-1"><h2 className="font-black">Сбросить настройки</h2><p className="text-sm text-muted">Вернуть параметры этого устройства по умолчанию</p></div><Button variant="danger" onClick={() => { setSettings(defaultSettings); saveSettings(defaultSettings); }}>Сбросить</Button></Card>
  </div>;
}
