import { CalendarDays, CarFront, ClipboardList, Pencil, UserRound } from "lucide-react";
import type { Appointment, Car, CrmData, Customer, Order } from "../../lib/types";
import { customerName, formatDateTime, money, statusLabel } from "../../lib/format";
import { Button, Modal } from "../../components/ui";
import type { EntityModalState } from "./EntityModal";

type Detail = { kind: "customer"; value: Customer } | { kind: "car"; value: Car } | { kind: "appointment"; value: Appointment } | { kind: "order"; value: Order };
export type DetailModalState = Detail | null;
type Props = { detail: Detail; data: CrmData; onClose: () => void; onEdit: (value: NonNullable<EntityModalState>) => void; onOpen: (value: Detail) => void };
const Row = ({ label, value }: { label: string; value: React.ReactNode }) => <div className="min-w-0 rounded-xl bg-panel-soft p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</dt><dd className="mt-1 break-words font-semibold">{value || "Не указано"}</dd></div>;

export function DetailModal({ detail, data, onClose, onEdit, onOpen }: Props) {
  if (detail.kind === "customer") {
    const cars = data.cars.filter((x) => x.customer_id === detail.value.id); const carIds = new Set(cars.map((x) => x.id));
    const orders = data.orders.filter((x) => carIds.has(x.car_id)); const visits = data.appointments.filter((x) => carIds.has(x.car_id));
    return <Modal title={customerName(detail.value.full_name)} onClose={onClose}><div className="grid gap-4"><dl className="grid gap-2 sm:grid-cols-2"><Row label="Телефон" value={detail.value.phone} /><Row label="Автомобилей" value={cars.length} /><Row label="Заказ-нарядов" value={orders.length} /><Row label="Общая прибыль" value={money(orders.reduce((sum, x) => sum + x.profit, 0))} /></dl><Related title="Автомобили" empty="Автомобили не добавлены">{cars.map((x) => <Link key={x.id} onClick={() => onOpen({ kind: "car", value: x })} icon={<CarFront />}>{x.brand} {x.model}{x.plate_number ? ` · ${x.plate_number}` : ""}</Link>)}</Related><Related title="Последние обращения" empty="Обращений пока нет">{[...visits].slice(0, 5).map((x) => <Link key={x.id} onClick={() => onOpen({ kind: "appointment", value: x })} icon={<CalendarDays />}>{formatDateTime(x.starts_at)} · {x.description}</Link>)}</Related><div className="flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={() => onEdit({ kind: "car", customerId: detail.value.id })}><CarFront size={17} />Добавить авто</Button><Button onClick={() => onEdit({ kind: "customer", value: detail.value })}><Pencil size={17} />Изменить</Button></div></div></Modal>;
  }
  if (detail.kind === "car") {
    const owner = data.customers.find((x) => x.id === detail.value.customer_id); const orders = data.orders.filter((x) => x.car_id === detail.value.id); const visits = data.appointments.filter((x) => x.car_id === detail.value.id);
    return <Modal title={`${detail.value.brand} ${detail.value.model}`} onClose={onClose}><div className="grid gap-4"><dl className="grid gap-2 sm:grid-cols-2"><Row label="Госномер" value={detail.value.plate_number} /><Row label="Год" value={detail.value.year} /><Row label="Пробег" value={detail.value.mileage ? `${detail.value.mileage.toLocaleString("ru-RU")} км` : null} /><Row label="VIN" value={<span className="break-all font-mono text-sm">{detail.value.vin || "Не указано"}</span>} /></dl>{owner && <Related title="Владелец"><Link onClick={() => onOpen({ kind: "customer", value: owner })} icon={<UserRound />}>{customerName(owner.full_name)}{owner.phone ? ` · ${owner.phone}` : ""}</Link></Related>}<Related title="История заказов" empty="Заказов пока нет">{orders.map((x) => <Link key={x.id} onClick={() => onOpen({ kind: "order", value: x })} icon={<ClipboardList />}>#{x.id} · {x.description} · {money(x.profit)}</Link>)}</Related><Related title="Записи" empty="Записей пока нет">{visits.slice(0, 5).map((x) => <Link key={x.id} onClick={() => onOpen({ kind: "appointment", value: x })} icon={<CalendarDays />}>{formatDateTime(x.starts_at)} · {x.description}</Link>)}</Related><div className="grid gap-2 sm:grid-cols-3"><Button variant="secondary" onClick={() => onEdit({ kind: "appointment", carId: detail.value.id })}>Новая запись</Button><Button variant="secondary" onClick={() => onEdit({ kind: "order", carId: detail.value.id })}>Новый заказ</Button><Button onClick={() => onEdit({ kind: "car", value: detail.value })}><Pencil size={17} />Изменить</Button></div></div></Modal>;
  }
  if (detail.kind === "appointment") return <Modal title={`Запись #${detail.value.id}`} onClose={onClose}><div className="grid gap-4"><dl className="grid gap-2 sm:grid-cols-2"><Row label="Дата и время" value={formatDateTime(detail.value.starts_at)} /><Row label="Статус" value={statusLabel(detail.value.status)} /><Row label="Автомобиль" value={`${detail.value.brand} ${detail.value.model}${detail.value.plate_number ? ` · ${detail.value.plate_number}` : ""}`} /><Row label="Клиент" value={customerName(detail.value.customer_name)} /><Row label="Телефон" value={detail.value.customer_phone} /><Row label="Согласовано" value={detail.value.agreed_amount == null ? null : money(detail.value.agreed_amount)} /><Row label="Запчасти" value={detail.value.parts_source === "workshop" ? "Наши" : detail.value.parts_source === "customer" ? "Клиента" : null} /><Row label="Гибкое время" value={detail.value.is_flexible ? "Да" : "Нет"} /></dl><Row label="Причина обращения" value={detail.value.description} /><Button onClick={() => onEdit({ kind: "appointment", value: detail.value })}><Pencil size={17} />Изменить запись</Button></div></Modal>;
  const o = detail.value; const markup = o.parts_revenue - o.parts_cost + o.parts_profit;
  return <Modal title={`Заказ-наряд #${o.id}`} onClose={onClose}><div className="grid gap-4"><dl className="grid gap-2 sm:grid-cols-2"><Row label="Автомобиль" value={`${o.brand} ${o.model}${o.plate_number ? ` · ${o.plate_number}` : ""}`} /><Row label="Клиент" value={customerName(o.customer_name)} /><Row label="Статус" value={statusLabel(o.status)} /><Row label="Создан" value={formatDateTime(o.created_at)} /><Row label="Работы" value={money(o.labor_revenue)} /><Row label="Закупка запчастей" value={money(o.parts_cost)} /><Row label="Продажа запчастей" value={money(o.parts_revenue)} /><Row label="Наценка запчастей" value={money(markup)} /><Row label="Общая выручка" value={money(o.labor_revenue + o.parts_revenue)} /><Row label="Итоговая прибыль" value={<span className="text-success">{money(o.profit)}</span>} /></dl><Row label="Жалоба клиента" value={o.concern} /><Row label="Выполненные работы" value={o.description} /><Row label="Рекомендации" value={o.recommendations} /><Button onClick={() => onEdit({ kind: "order", value: o })}><Pencil size={17} />Изменить заказ-наряд</Button></div></Modal>;
}
function Related({ title, children, empty }: React.PropsWithChildren<{ title: string; empty?: string }>) { const count = Array.isArray(children) ? children.length : children ? 1 : 0; return <section><h3 className="mb-2 font-black">{title}</h3><div className="grid gap-2">{count ? children : <p className="rounded-xl bg-panel-soft p-3 text-sm text-muted">{empty}</p>}</div></section>; }
function Link({ children, icon, onClick }: React.PropsWithChildren<{ icon: React.ReactNode; onClick: () => void }>) { return <button type="button" onClick={onClick} className="flex min-w-0 items-center gap-3 rounded-xl bg-panel-soft p-3 text-left text-sm transition hover:bg-line"><span className="shrink-0 text-apex">{icon}</span><span className="min-w-0 break-words">{children}</span></button>; }
